### ISSUE TITLE
Use a config file system

### ISSUE THREAD

**Issue by Bisaloo** [reichlab/covidHubUtils#240]
Currently, most functions of this package require specifying the same argument throughout scripts (such as `source`, `hub_repo_path`, `hub`).

This is typo-prone (e.g., #228), difficult to update (e.g., in the case of a migration from a `"local_hub_repo"` to Zoltar).

Additionally, the `hub` argument from which is derived information like `possible_locations` makes it difficult for someone to spin a new hub without extra work from your end.

Instead of this, I propose to use use a config file that would contain all the metadata about the hub. Below is an example of some information that could be stored in a YAML file:

```yml
source: local_hub_repo
hub_repo_path: https://raw.githubusercontent.com/epiforecasts/covid19-forecast-hub-europe/main
hub_locations: data-locations/locations_eu.csv
verbose: false
```

This suggestion is inspired from the way pkgdown handles this problem of arguments that will remain the same throughout the project.
